# Generated by Django 3.2.18 on 2023-05-27 13:36

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.RichTextBlock()), ('description', wagtail.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('button_text', wagtail.blocks.CharBlock(max_length=1000)), ('button_link', wagtail.blocks.URLBlock()), ('enable', wagtail.blocks.BooleanBlock(default=True))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='case_studies',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.CharBlock(max_length=1000)), ('list_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=1000)), ('description', wagtail.blocks.TextBlock()), ('thumbnail', wagtail.images.blocks.ImageChooserBlock()), ('video', wagtail.blocks.URLBlock()), ('enable', wagtail.blocks.BooleanBlock(default=True))])))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features',
            field=wagtail.fields.StreamField([('list_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock(max_length=1000)), ('description', wagtail.blocks.TextBlock()), ('link', wagtail.blocks.URLBlock()), ('active', wagtail.blocks.BooleanBlock(default=True))]))), ('enable', wagtail.blocks.BooleanBlock(default=True))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer',
            field=wagtail.fields.StreamField([('description', wagtail.blocks.TextBlock()), ('facebook_contact', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock()), ('enable', wagtail.blocks.BooleanBlock(default=True))])), ('instagram_contact', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock()), ('enable', wagtail.blocks.BooleanBlock(default=True))])), ('linkedin_contact', wagtail.blocks.StructBlock([('url', wagtail.blocks.URLBlock()), ('enable', wagtail.blocks.BooleanBlock(default=True))])), ('list_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=1000)), ('item', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=1000)), ('link', wagtail.blocks.URLBlock())]))), ('enable', wagtail.blocks.BooleanBlock(default=True))]))), ('location', wagtail.blocks.TextBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='menu',
            field=wagtail.fields.StreamField([('key_selling_points', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=1000)), ('enable', wagtail.blocks.BooleanBlock(default=True))])), ('why', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=1000)), ('enable', wagtail.blocks.BooleanBlock(default=True))])), ('mission', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=1000)), ('enable', wagtail.blocks.BooleanBlock(default=True))])), ('proof_points', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=1000)), ('enable', wagtail.blocks.BooleanBlock(default=True))])), ('services', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=1000)), ('enable', wagtail.blocks.BooleanBlock(default=True))])), ('case_studies', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=1000)), ('enable', wagtail.blocks.BooleanBlock(default=True))])), ('testimonials', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=1000)), ('enable', wagtail.blocks.BooleanBlock(default=True))])), ('subscription_form', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=1000)), ('enable', wagtail.blocks.BooleanBlock(default=True))]))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission',
            field=wagtail.fields.StreamField([('list_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock(max_length=1000)), ('description', wagtail.blocks.TextBlock()), ('enable', wagtail.blocks.BooleanBlock(default=True))]))), ('enable', wagtail.blocks.BooleanBlock(default=True))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='proof_points',
            field=wagtail.fields.StreamField([('list_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('number', wagtail.blocks.IntegerBlock(max_length=1000)), ('description', wagtail.blocks.TextBlock()), ('enable', wagtail.blocks.BooleanBlock(default=True))])))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock(max_length=1000)), ('description', wagtail.blocks.TextBlock()), ('list_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock(max_length=1000)), ('description', wagtail.blocks.TextBlock()), ('enable', wagtail.blocks.BooleanBlock(default=True))]))), ('enable', wagtail.blocks.BooleanBlock(default=True))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subscription_form',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.CharBlock(max_length=1000)), ('description', wagtail.blocks.TextBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.CharBlock(max_length=1000)), ('description', wagtail.blocks.TextBlock()), ('list_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock()), ('user_avatar', wagtail.images.blocks.ImageChooserBlock()), ('user_name', wagtail.blocks.TextBlock()), ('enable', wagtail.blocks.BooleanBlock(default=True))])))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why',
            field=wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock(max_length=1000)), ('description', wagtail.blocks.TextBlock()), ('list_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock(max_length=1000)), ('description', wagtail.blocks.TextBlock()), ('enable', wagtail.blocks.BooleanBlock(default=True))]))), ('enable', wagtail.blocks.BooleanBlock(default=True))], blank=True, use_json_field=True),
        ),
    ]
