# Generated by Django 3.2.18 on 2023-05-27 21:32

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_auto_20230527_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='logo',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='mission',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.CharBlock(max_length=1000)), ('description', wagtail.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('list_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock(max_length=1000)), ('description', wagtail.blocks.TextBlock()), ('enable', wagtail.blocks.BooleanBlock(default=True, required=False))]))), ('enable', wagtail.blocks.BooleanBlock(default=True, required=False))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='why',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.CharBlock(max_length=1000)), ('description', wagtail.blocks.TextBlock()), ('list_items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.blocks.CharBlock(max_length=1000)), ('description', wagtail.blocks.TextBlock()), ('enable', wagtail.blocks.BooleanBlock(default=True, required=False))]))), ('enable', wagtail.blocks.BooleanBlock(default=True, required=False))], blank=True, use_json_field=True),
        ),
    ]
