# Generated by Django 3.2.16 on 2023-06-04 16:46

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_auto_20230528_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner',
            field=wagtail.fields.StreamField([('title', wagtail.blocks.RichTextBlock()), ('description', wagtail.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('background_image', wagtail.images.blocks.ImageChooserBlock()), ('button_text', wagtail.blocks.CharBlock(max_length=1000)), ('button_link', wagtail.blocks.URLBlock()), ('enable', wagtail.blocks.BooleanBlock(required=False))], blank=True, default=[('enable', True)], use_json_field=True),
        ),
    ]
